package:
  name: boxlib
  version: 0.1.0

source:
  path: ..

requirements:
  host:
    - python
  run:
    - python
    - numpy

about:
  home: https://github.com/isarandi/boxlib
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Utilities for bounding box manipulation'
  description: |
    Utilities for bounding box manipulation in computer vision
  dev_url: https://github.com/isarandi/boxlib
  doc_url: https://github.com/isarandi/boxlib
  doc_source_url: https://github.com/isarandi/boxlib/blob/main/README.md
